### ISSUE TITLE
What the meaning of this code

### ISSUE THREAD

**Issue by gmuc** [reactbuch/vote-example#18]
test/unit/actions/actions.spec.js

```
const mockFetchJson = (result) => {
    spyOn(Backend, 'fetchJson')
      .andReturn({
        then(fn) {   <=== what the meaning of this, what is "then"
          fn(result);
        }
      });
  };
```
next question:
```
  it('should create SET_VOTES action', () => {
    mockFetchJson(rawVotes);

    const fn = actions.loadVotes(); <=== why define fn here? fn is used in mockFetchJson > I expect the definition of fn before calling mockFetchJson???

    fn(dispatch);
    expect(dispatch).toHaveBeenCalledWith({type: actions.SET_VOTES, votes: rawVotes});
});
```
Thank you!

**Comment by nilshartmann** [comment]
Hi!

`then` in the first snippet: The mock-function for "fetchJson" must return "something that looks like a Promise". And a promise consists - among other - of a `then` function. And as we only use the `then` function in the code tested by the test case, we simply return an object with a "mock" then function.

`fn`: `loadVotes` returns a function that expectes a `dispatch` function (redux-thunk). The function than is invoked in the next line. Explicitly assign fn is not really necessary, so that the code could be rewritten to:
```
actions.loadVotes()(dispatch)
```

Don't know if that's better. Would maybe a good idea to rename `fn` to `loadVotesAction` or something like this.

Hope that helps!

**Comment by gmuc** [comment]
I hope I understand:

1. create a mock for "fetchJson" include mocking "then" by using ES6 shorthand
2. set fn to function pointer of actions.loadVotes
3. call actions.loadVotes function pointer with dispatch function (spied by createSpy) as argument
4. actions.loadVotes processing use the previous defined mocks (fetchJson + then)
5. expect + toHaveBeenCalledWith test the argument-values of the dispatch call inside of loadVotes

The toHaveBeenCalledWith only work if dispatch is spied by createSpy.

RIGHT?

(the structure of the demo source for your book is excellent. Good job!!!)

**Comment by nilshartmann** [comment]
Yes, that's right!

BTW: If I'd start a (React) project today, I would use Jest for testing, which is currently the de-factory standard for testing React applications.

With jest you don't need to configure JSDom (as it's built in) and there is also mock support built-in:
* https://jestjs.io/docs/en/mock-functions
* https://jestjs.io/docs/en/manual-mocks

Esp for testing async code with Jest I built some example (not very much up-to-date anymore, but most things should still work): https://github.com/nilshartmann/jest-playground

Hope that helps!

**Comment by gmuc** [comment]
Whats your opinion in the Relay vs Apollo discussion?

**Comment by nilshartmann** [comment]
Disclaimer: I have not used Relay yet.

I think Apollo is more mainstream than Relay, that's why I'd go with Apollo. 

On the other hand: I don't really like the "manage your local state with apollo" approach. Using Apollo as a cache for your data you have loaded with GraphQL might be fine, but I would avoid storing local data in the Apollo Cache (doesn't like neither the API nor the idea in general)

**Comment by gmuc** [comment]
Klingt logischen. Danke für die Einschätzung. Es ist leider immer sehr aufwändig eine eigene Einschätzung mit eigenem Wissen treffen zu können. 
Ich bin von Ihrem Buch begeistert und das beste überhaupt ist der Sourcecode dazu. Ich hoffe, es kommt irgendwann eine aktualisierte Auflage :-)
